reload('user.plugins')
reload('user.colorscheme')
reload('user.options')
reload('user.keymaps')
reload('user.which-key')
reload('user.statusline')
reload('user.lsp')
reload('user.dashboard')
reload('user.cmp')
reload('user.bufferline')
reload('user.colorizer')
reload('user.telescope')
reload('user.nvimtree')
reload('user.lualine')
-- reload('user.scrollbar')
-- reload('user.lsp-status')
reload('user.autocmds')
