icons_format = "{icon}"

[theme]
theme = "dracula"
[theme.overrides]
# idle_bg = "#123456"
# idle_fg = "#abcdef"
good_fg = { link = "warning_fg" }
good_bg = { link = "warning_bg" }
warning_fg = { link = "good_fg" }
warning_bg = { link = "good_bg" }

[icons]
icons = "awesome4"
[icons.overrides]
bat = " | | "
bat_full = " |X| "
bat_charging = " |^| "
bat_discharging = " |v| "

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 5
warning = 20.0
alert = 10.0
format = " $icon $available.eng(w:2) "
[[block.click]]
button = "left"
cmd = "thunar"

[[block]]
block = "memory"
format = " $icon $mem_used/$mem_total "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %d/%m %R') "
